services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./app/:/go/src/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15.2-alpine
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB || exit 1"
        ]
      interval: 1s
      timeout: 3s
      retries: 30
    restart: always

volumes:
  dbdata: null
